name: Moonsea Codex API

on:
  push:
    branches:
      - main

jobs:
  Build-Docker-Container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/moonseacodex-api:live

  Deploy-To-Server:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: Build-Docker-Container

    steps:
      - name: Create database backup
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.SERVER }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker exec -it {{ secrets.DB_HOST }} pg_dumpall -U {{ secrets.DB_USER }} > {{ vars.DB_BACKUP_PATH }}

      - name: Deploy new container
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.SERVER }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker pull ${{ vars.DOCKERHUB_USERNAME }}/moonseacodex-api:live
            docker stop api || true
            docker rm  api || true
            docker run -d --name api --network=moonseacodex-net -p 127.0.0.1:4000:4000 \
              -e DJANGO_SECRET=${{ secrets.DJANGO_SECRET }} -e DB_HOST=${{ secrets.DB_HOST }} \
              -e DB_USER=${{ secrets.DB_USER }} -e DB_PASS=${{ secrets.DB_PASS }} \
              -e SERVER=${{ vars.SERVER }} -e DOMAIN=${{ vars.SERVER }} \
              -e EMAIL_API_KEY=${{secrets.EMAIL_API_KEY}} -e DEFAULT_EMAIL_SENDER=${{ secrets.DEFAULT_EMAIL_SENDER }} \
              -v /moonseacodex/media:/moonseacodex_api/media \
              --restart=always ${{ vars.DOCKERHUB_USERNAME }}/moonseacodex-api:live
      
      - name: Perform database migrations
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.SERVER }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker exec -it api python manage.py migrate
